name: Upload coverage on push
on:
  push:
    branches: ['main']
jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: yarn install --immutable
      - run: yarn run test
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
